# Generated by Django 2.1.2 on 2018-11-16 09:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_post_date_update'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='date_publish',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
